kind: PersistentVolume
apiVersion: v1
metadata:
 name: pgstorage
 namespace: default
spec:
 storageClassName: hostpath
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/tmp"
