apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: db-postgres
  namespace: default
spec:
  teamId: "db"
  volume:
    size: 1Gi
    storageClass: hostpath
  numberOfInstances: 2
  users:
    zalando: # database owner
    - superuser
    - createdb
    foo_user: [] # role for application foo
  databases:
    foo: zalando # dbname: owner
  postgresql:
    version: "10"
